name: Build Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SurfBindsPlugin.csproj

    - name: Build plugin
      run: dotnet build SurfBindsPlugin.csproj --configuration Release

    - name: Upload plugin DLL
      uses: actions/upload-artifact@v4
      with:
        name: SurfBindsPlugin
        path: |
          ./bin/Release/net8.0/*.dll
